### ISSUE TITLE
Newbie - stuck on syntax errors

### ISSUE THREAD

**Issue by nikgilbe** [rgraciano/echo-sonos#100]
Hi folks. I've tried this a few times now - everything is OK up until I go to test the Lambda function, and for the life of me I can't figure out what's wrong. Zip file created without /src, I've checked the index.js etc in Notepad++ and all looks OK but I keep getting this syntax error:

Syntax error in module 'index': SyntaxError
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/index.js:18:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

If anyone can help I would be extremely grateful

Thanks

**Comment by nikgilbe** [comment]
After looking again, my Alexaskill.js was invalid - I must have miscopied that first time round.
