### ISSUE TITLE
New lambda code with environment variables - I can not get this to work. Help needed.

### ISSUE THREAD

**Issue by GregRocket** [rgraciano/echo-sonos#116]
I've zipped up and uploaded new files leaving options.js unedited. In Lampda Management Console I added the Environment Variables. 

When I run the test I get this error:
{ "errorMessage": "RequestId: xxx... Process exited before completing request" }

I am using a Raspberry PI 3

**Comment by GregRocket** [comment]
**Log Output (Old method with edited options.js):**
START RequestId: 3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd Version: $LATEST 2017-01-28T17:21:41.637Z 

3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd session applicationId: 

amzn1.echo-sdk-ams.app.xxx 2017-01-28T17:21:41.637Z 

3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd dispatch intent = PlayPresetIntent 2017-01-28T17:21:41.637Z 

3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd PlayPresetIntent received 2017-01-28T17:21:41.637Z 

3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd Sending HTTP request to: /preset/test END RequestId: 

3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd REPORT RequestId: 3bfa543a-e57e-11e6-9ba2-5bae4e1b91cd Duration: 206.14 ms 

Billed Duration: 300 ms Memory Size: 128 MB Max Memory Used: 26 MB

**Log Output (New metod with unedited options.js and environment variables):**
START RequestId: 89ef7414-e57e-11e6-be3d-6768b0c930a1 Version: $LATEST 2017-01-28T17:23:52.905Z 

89ef7414-e57e-11e6-be3d-6768b0c930a1 session applicationId: 

amzn1.echo-sdk-ams.app.dexxx 2017-01-28T17:23:52.906Z

89ef7414-e57e-11e6-be3d-6768b0c930a1 dispatch intent = PlayPresetIntent 2017-01-28T17:23:52.906Z 

89ef7414-e57e-11e6-be3d-6768b0c930a1 PlayPresetIntent received 2017-01-28T17:23:53.724Z 

89ef7414-e57e-11e6-be3d-6768b0c930a1 sending SQS /preset/test 2017-01-28T17:23:53.986Z 

89ef7414-e57e-11e6-be3d-6768b0c930a1 { ResponseMetadata: { RequestId: '607b2efc-494d-5cc0-b95f-7ffa9ca45c61' }, 

MD5OfMessageBody: '8649d9f57abd38d219cc0ac60a902e53', MessageId: '2c0f4b62-16fa-4f00-b301-39f243e49e4c' } 

2017-01-28T17:24:14.564Z 89ef7414-e57e-11e6-be3d-6768b0c930a1 TypeError: Cannot read property '0' of undefined at Response.<anonymous> (/var/task/index.js:719:60) at Request.<anonymous> 

(/var/runtime/node_modules/aws-sdk/lib/request.js:355:18) at Request.callListeners 

(/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit 

(/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit 

(/var/runtime/node_modules/aws-sdk/lib/request.js:668:14) at Request.transition 

(/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo 

(/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> 

(/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> 

(/var/runtime/node_modules/aws-sdk/lib/request.js:670:12) END RequestId: 89ef7414-e57e-11e6-be3d-6768b0c930a1 

REPORT RequestId: 89ef7414-e57e-11e6-be3d-6768b0c930a1 Duration: 21843.27 ms Billed Duration: 21900 ms Memory 

Size: 128 MB Max Memory Used: 34 MB RequestId: 89ef7414-e57e-11e6-be3d-6768b0c930a1 Process exited before completing request

**Comment by GregRocket** [comment]
I noticed the test was trying to send sqs rrquest instead of http.  I am not using  sqs. 

I had enviroment variable set for sqs to false. I tried just leaving setting to blank and then the test worked. I'm going to close this issue and start a new one.
