### ISSUE TITLE
Alexa not responding...

### ISSUE THREAD

**Issue by loftgren** [rgraciano/echo-sonos#148]
Hi All... when I ask Alexa to play music, I get this response.  It says the connection attempt to my server failed.  Yet I passed the tests in Lambda etc.  When I ask Alexa to pause music, she says "ok" but the music does not pause.  Any help greatly appreciated!

2017-04-03T20:40:27.394Z	c4c62cbb-18ad-11e7-9c4d-e78260c21b8c	{ Error: getaddrinfo ENOTFOUND myserver.local:5005
at errnoException (dns.js:28:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'myserver.local',
host: 'myserver.local',
port: '5005' }

**Comment by loftgren** [comment]
2017-04-03T20:40:27.394Z	c4c62cbb-18ad-11e7-9c4d-e78260c21b8c	Call to 'http://myserver.local:5005/zones' failed
