### ISSUE TITLE
Everything works except song won't start

### ISSUE THREAD

**Issue by ncosper** [rgraciano/echo-sonos#155]
Not sure what Im missing here but when sonos hasn't been played for a while and I try and start up a song it won't start. It adds the song to the queue, sends the correct url to the server but I get a 500 error at clientrequest.lib.get. Not sure what the error means but the player just won't start. If I start it using either the desktop or mobile app then I can pause and resume just fine, change songs, volume etc, just cant start after nothing has played in a while. 
Here is the log:

21:03:22
REPORT RequestId: 7688f401-1fc3-11e7-822e-9d18fb3cb4f1	Duration: 351.67 ms	Billed Duration: 400 ms Memory Size: 128 MB	Max Memory Used: 30 MB

21:08:32
START RequestId: 2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d Version: $LATEST

21:08:32
2017-04-12T21:08:32.604Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	session applicationId: amzn1.ask.skill.607ea852-e3a5-4867-bffa-5b01fd17e70c

21:08:32
2017-04-12T21:08:32.604Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	dispatch intent = ArtistIntent

21:08:32
2017-04-12T21:08:32.605Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	ArtistIntent received for room undefined

21:08:32
2017-04-12T21:08:32.605Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Advanced Mode = true

21:08:32
2017-04-12T21:08:32.879Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Reading current settings

21:08:32
2017-04-12T21:08:32.919Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	room=house newRoom= service=apple newService=

21:08:32
2017-04-12T21:08:32.919Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Getting coordinator for room: house

21:08:32
2017-04-12T21:08:32.919Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Calling '/zones'

21:08:33
2017-04-12T21:08:33.125Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Call to 'http://xxxxx.ddns.net:5005/zones' suceeded

21:08:33
2017-04-12T21:08:33.125Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Coordinator for house : house

21:08:33
2017-04-12T21:08:33.126Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Calling '/house/musicsearch/apple/song/artist:Paul%20McCartney'

21:08:35
2017-04-12T21:08:35.094Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Call to 'http://xxxxx.ddns.net:5005/house/musicsearch/apple/song/artist:Paul%20McCartney' failed

21:08:35
2017-04-12T21:08:35.094Z	2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d	Error: Failed to retrieve data, status code: 500 at ClientRequest.lib.get (/var/task/sonosProxy/httpClient.js:13:17) at ClientRequest.g (events.js:291:16) at emitOne (events.js:96:13) at ClientRequest.emit (events.js:188:7) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21) at HTTPParse

21:08:35
END RequestId: 2f3f54e0-1fc4-11e7-8a75-d3e5f709da1d

**Comment by loftgren** [comment]
I am having the exact same problem.  My log looks the same as above.  At this point I can only play music in one room, unless I group others to that room.  Please help.

**Comment by pheintzelman** [comment]
What happens when you call http://xxxxx.ddns.net:5005/house/musicsearch/apple/song/artist:Paul%20McCartney' directly?

**Comment by loftgren** [comment]
When I call http://xxxxx.ddns.net:5005/house/musicsearch/apple/song/artist:Paul%20McCartney directly I get the following:

{"status":"error","error":"You are missing spotify clientId and secret in settings.json! Please read the README for instructions on how to generate and add them","stack":"Error: You are missing spotify clientId and secret in settings.json! Please read the README for instructions on how to generate and add them\n    at getHeaders (/Users/christophermurray/node-sonos-http-api-master/lib/music_services/spotifyDef.js:66:11)\n    at getOptions (/Users/christophermurray/node-sonos-http-api-master/lib/music_services/spotifyDef.js:78:14)\n    at auth (/Users/christophermurray/node-sonos-http-api-master/lib/music_services/spotifyDef.js:88:19)\n    at Promise (/Users/christophermurray/node-sonos-http-api-master/lib/music_services/spotifyDef.js:110:5)\n    at authenticateService (/Users/christophermurray/node-sonos-http-api-master/lib/music_services/spotifyDef.js:109:10)\n    at doSearch (/Users/christophermurray/node-sonos-http-api-master/lib/actions/musicSearch.js:133:12)\n    at getAccountId.then (/Users/christophermurray/node-sonos-http-api-master/lib/actions/musicSearch.js:215:14)\n    at tryCatcher (/Users/christophermurray/node-sonos-http-api-master/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/Users/christophermurray/node-sonos-http-api-master/node_modules/bluebird/js/main/promise.js:510:31)\n    at Promise._settlePromiseAt (/Users/christophermurray/node-sonos-http-api-master/node_modules/bluebird/js/main/promise.js:584:18)\n    at Async._drainQueue (/Users/christophermurray/node-sonos-http-api-master/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/Users/christophermurray/node-sonos-http-api-master/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues (/Users/christophermurray/node-sonos-http-api-master/node_modules/bluebird/js/main/async.js:15:14)\n    at runCallback (timers.js:651:20)\n    at tryOnImmediate (timers.js:624:5)\n    at processImmediate [as _immediateCallback] (timers.js:596:5)"}

**Comment by jzajac2** [comment]
I can recreate this issue when I remove my spotify clientId and secretId from settings.json. You should have a settings.json at root folder:

`{
  "port": 5005,
  "securePort": 5006
}
    `

You need to add after the '6' in '5006':
`,
  "spotify": {
      "clientId": "e6ebb7f5c7f4477d84f66edfa86e3641",
      "clientSecret": "YOURSECRETHERE",
  }`

Takes just a few minutes to log into spotify and create an 'app' and create the keys.
Try that? Simply go to: [https://developer.spotify.com/my-applications/#!/applications/create](here) , login, and to get your client secret click the 'show client secret' button. Put that in your settings.json

![clientspotifysecret](https://user-images.githubusercontent.com/101703/35844046-0011cf18-0ad1-11e8-99eb-a699e7d77b28.PNG)
