### ISSUE TITLE
All works only when grouped... not individually

### ISSUE THREAD

**Issue by loftgren** [rgraciano/echo-sonos#158]
Everything works flawlessly, but only when other speakers are grouped to kitchen.  I do have kitchen as default in lambda. When I try to play music on anything other than kitchen, Alexa says it is playing but no sound is produced, and in the logs I get a code 500.  

2017-04-20T14:28:25.749Z	9cf3e265-25d5-11e7-a146-0d6e3d97d126	Calling '/dining%20room/musicsearch/spotify/song/artist:Willie%20Nelson'

14:28:26
2017-04-20T14:28:26.467Z	9cf3e265-25d5-11e7-a146-0d6e3d97d126	Call to 'http://24.93.140.222:5005/dining%20room/musicsearch/spotify/song/artist:Willie%20Nelson' failed
2017-04-20T14:28:26.467Z	9cf3e265-25d5-11e7-a146-0d6e3d97d126	Call to 'http://24.93.140.222:5005/dining%20room/musicsearch/spotify/song/artist:Willie%20Nelson' failed

14:28:26
2017-04-20T14:28:26.467Z	9cf3e265-25d5-11e7-a146-0d6e3d97d126	Error: Failed to retrieve data, status code: 500 at ClientRequest.lib.get (/var/task/sonosProxy/httpClient.js:13:17) at ClientRequest.g (events.js:291:16) at emitOne (events.js:96:13) at ClientRequest.emit (events.js:188:7) at HTTPParser.parserOnIncomingClient (_http_client.js:473:21) at HTTPParser.parserOnHeader
2017-04-20T14:28:26.467Z	9cf3e265-25d5-11e7-a146-0d6e3d97d126	Error: Failed to retrieve data, status code: 500
at ClientRequest.lib.get (/var/task/sonosProxy/httpClient.js:13:17)
at ClientRequest.g (events.js:291:16)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
at Socket.socketOnData (_http_client.js:362:20)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)

If i do the same process with the kitchen, all works perfectly.  I have directed Alexa to change room and service, which she says she does, and then she says she is playing in the new room, but no music plays.

Any help truly appreciated!

**Comment by pheintzelman** [comment]
hmm that is odd. Did you set defaultLinein by mistake?
