### ISSUE TITLE
'The specified queue does not exist for this wsdl version.'

### ISSUE THREAD

**Issue by youdy** [rgraciano/echo-sonos#165]
Been trying to figure this out for a few days now and no cigar, I know its probably something silly. 
```2017-06-03T12:11:22.872Z		PlayPresetIntent received
2017-06-03T12:11:22.872Z		Sending SQS '/preset/test'
2017-06-03T12:11:23.851Z		SQS didn't purged queue
2017-06-03T12:11:24.032Z		SQS failed to send message /preset/test
2017-06-03T12:11:24.032Z		SQS '/preset/test' failed
2017-06-03T12:11:24.032Z		{ AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The specified queue does not exist for this wsdl version.',
  code: 'AWS.SimpleQueueService.NonExistentQueue',
  time: 2017-06-03T12:11:24.031Z,```

**Comment by erlichson** [comment]
also been investigating this. I have USE_SQS to false, and that's the default. So it's not clear why it's invoking the SQS code at all.
