### ISSUE TITLE
Invocation

### ISSUE THREAD

**Issue by donwatermelon** [rgraciano/echo-sonos#181]
Hi All,

Great to meet you all. Seriously new to echo, GitHub and coding et all in general but definitely looking to spend more time on this side of the world. It's awesome! :-)

So I've got a problem whereby I've configured everything the way I think I should, whenever I "Alexa" a song to any Sonos, it says it's starting but does nothing. So if I were to say "Alexa, ask Sonos to play Michael Jackson, Alexa responds and says it's starting to play Michael Jackson but nothing can be heard from the speakers or the dot (can't see anything running in the Sonos app either). All I see in the terminal session running npm is this:

2017-06-18T14:03:57.413Z INFO http server listening on port 5005
2017-06-18T14:04:50.246Z ERROR 
  StatusCodeError: 401 - [object Object]
    at new StatusCodeError (/home/pi/node-sonos-http-api/node_modules/request-promise/lib/errors.js:26:15)
    at Request.RP$callback [as _callback] (/home/pi/node-sonos-http-api/node_modules/request-promise/lib/rp.js:68:32)
    at Request.self.callback (/home/pi/node-sonos-http-api/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/pi/node-sonos-http-api/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/pi/node-sonos-http-api/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

Lambda service appears to be configured fine and tests without issue (invocations can be seen in the dashboard). The Alexa skills have been created and installed on the Echo Dot without issue but still nothing beyond

In terms of setup, I'm running the latest version echo-sonos file set on a Raspberry Pi Zero; 64Mb, Debian (Jessie) v8, node v.4.2.4, pm 5.0.3 and 6 x Sonos Play:1 grouped together (for testing purposes) with a few Echo Dot's "dotted around". I've tried it on a Raspberry Pi B as well with the same result.

Any ideas or suggestions? Would appreciate any help, advice or suggestions. Happy to send more useful logs if required/request.

Thanks in advance everyone.
DW

**Comment by donwatermelon** [comment]
Okay. I've sort of half fixed my problem where the invocation works and it does start playlists but doesn't when requesting specific artists or rooms (e.g. "Kitchen" works but "Back Bedroom" 

I've got a long list of artists and rooms in my Alexa NAMES and ROOMS interactions models. Are there any limitations on the format these need to take, .e.g. spaces between room names, capitalizations of rooms or artists names, etc.?
