### ISSUE TITLE
Lamba errors. Help. Error log posted

### ISSUE THREAD

**Issue by eyoung71** [rgraciano/echo-sonos#75]
{
  "errorMessage": "Unexpected token <",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Module._compile (module.js:373:25)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

**Comment by eyoung71** [comment]
Is the only way to save the 3 needed files to right click on save? I tried opening in github and copy and pasting. I tried raw. I tried a dozen different ways. 
I have no idea how to proceed. I tried on a Mac and on a windows pc. I downloaded the 3 files and edited the options.js. Zipped and loaded. I did it about 10 times. No clue. 
Frustrating to fail on the last step.

**Comment by eyoung71** [comment]
I have a more detailed log here:

Syntax error in module 'index': SyntaxError
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

**Comment by eyoung71** [comment]
I solved it by using Atom to edit on my Mac.
Thanks. Awesome work.
